### ISSUE TITLE
Couldn't find preset "babel-preset-expo" relative to directory "/node_modules/react-native-swipe-hidden-header"

### ISSUE THREAD

**Issue by pvsousalima** [fengliu222/react-native-swipe-hidden-header#1]
I am having this issue described above. 

Is there any way to fix it? It looks like babel configuration type?

![simulator screen shot may 19 2017 12 44 07 am](https://cloud.githubusercontent.com/assets/1810178/26232404/65cf5ae2-3c2c-11e7-82d3-3f92e197ef5d.png)

**Comment by fengliu222** [comment]
I will fix this bug in few days, thank you.

**Comment by fengliu222** [comment]
Hey, please update to 0.1.1 and try again ~
